upstreams=["http://nginx:80"]
reverse_proxy=true
cookie_httponly=true
request_logging=true
auth_logging=true
standard_logging=true
session_store_type="redis"
redis_connection_url="redis://redis:6379/2"
skip_provider_button=true
set_xauthrequest=true
pass_authorization_header=true
pass_access_token=true
insecure_oidc_allow_unverified_email=true
provider="keycloak-oidc"
redirect_url="http://localhost/oauth2/callback"
oidc_issuer_url="https://your-keycloak-domain/realms/master"
code_challenge_method="S256"
email_domains="*"
http_address="http://0.0.0.0:8000"
cookie_refresh="0h4m0s"
cookie_expire="720h0m0s"